### ISSUE TITLE
Create logfile only on debugging mode

### ISSUE THREAD

**Issue by adpe** [PlagScan/PlagScan_moodle#13]
Hello @JesGor 

Would be a great feature if you can enable debugging mode in your plugin and only then will be the plagscan.log file created. And it would be better located inside `moodledata/plagscan` or something like that.

Greets
Adrian

**Comment by adpe** [comment]
Hi @JesGor 

As I see you have changed in 732270384b5be4de1f0494c250a8563ca0c8f410 the log handling. So it's now stored in the Moodle log database. Thanks for that change! I think this issue can be marked as closed.

**Comment by JesGor** [comment]
Thanks for your feedback @adpe 

We keep working on our software, always trying to improve and help our customers.
