### ISSUE TITLE
Hook for student disclosure is shown in forum activity

### ISSUE THREAD

**Issue by adpe** [PlagScan/PlagScan_moodle#15]
This message should only be displayed in `assign` activities. As the plugin don't supports forum inline-text verification or yes?

![image](https://user-images.githubusercontent.com/9467708/62458948-75b3f100-b77e-11e9-9668-3387ecdb622b.png)

If it does, then you must implement these settings that the user can enable/disable this functionality.

Greets,
Adrian

**Comment by rolmedoh** [comment]
There was a version that works with forum activities. That is why that message there but I disabled it after customers complain about it. That disclosure there should gone for sure. PS: Sorry for the delay here we where pretty busy

**Comment by adpe** [comment]
Furthermore, this message is displayed as well in `assign` activities where PlagScan is _not_ enabled.

It looks like it is displayed always! Please fix it...

**Comment by JesGor** [comment]
Please check the latest commit https://github.com/PlagScan/PlagScan_moodle/commit/9be03a411a0c8fd4f09876f77f6d896e983199c2 and version, we hope it solves the problem showing the disclosure, not only for other activies, but also for assignments where PlagScan was not enabled.

Sorry for the inconvinience. We appreciate the feedback.

**Comment by adpe** [comment]
It works now as expected.
