### ISSUE TITLE
Untranslatable menu items

### ISSUE THREAD

**Issue by koenr** [PlagScan/PlagScan_moodle#16]
Some strings don't show up in Amos - the Moodle tool to translate Moodle and Moodle plugins and therefore can't be translated the way they should:

useplagscan_filessubmission/plagiarism_plagscan
exclude_self_matches/plagiarism_plagscan
exclude_from_repository/plagiarism_plagscan
runsubmitmanual/plagiarism_plagscan

Here is the last import I could find in Amos:

Date:      2019-02-08 17:24 UTC
Author:    Jesus P.L. <jesusgorillo@gmail.com>
Source:    import

Strings for PlagScan Plagiarism Checker 3.0.2

+  3.6 en        [always,plagiarism_plagscan]
-  3.6 en        [analyze,plagiarism_plagscan]
+  3.6 en        [check,plagiarism_plagscan]
+  3.6 en        [checkstatus,plagiarism_plagscan]
+  3.6 en        [plagscan,plagiarism_plagscan]
+  3.6 en        [savedapiconfigerror_admin_email,plagiarism_plagscan]
+  3.6 en        [show_to_students_always,plagiarism_plagscan]
+  3.5 en        [always,plagiarism_plagscan]
-  3.5 en        [analyze,plagiarism_plagscan]
+  3.5 en        [check,plagiarism_plagscan]
+  3.5 en        [checkstatus,plagiarism_plagscan]
+  3.5 en        [plagscan,plagiarism_plagscan]
+  3.5 en        [savedapiconfigerror_admin_email,plagiarism_plagscan]
+  3.5 en        [show_to_students_always,plagiarism_plagscan]

**Comment by rolmedoh** [comment]
Sorry for the delay. I just checked and we should do somthing about this. I will check if someone from the translation team can work with AMOS

**Comment by koenr** [comment]
Thanks  - I checked the langauge file and compared it with what is in Amos and I can't see an obvious reason. I first thought the mixed use of double quotes and single quotes would be a problem, but doesn't seem to be, since there are strings in Amos, using double quotes.
I found there are 186 strings in Amos and 198 in the en language file, so 12 that are for some reason not picked up by amos.
If I can help, please ask.

**Comment by koenr** [comment]
I completely forgot about this, stumbled over it again, reinvestigated, wanted to file an issue and found my own :-)
So this issue is still there. I noticed that in the plugin directory the version  support is 3.8, but Amos only has strings up to 3.6 - just to add some information.

**Comment by koenr** [comment]
![Schermafdruk van 2020-05-07 11-03-29](https://user-images.githubusercontent.com/2964998/81275814-7a317100-9052-11ea-932e-1d5a2f6fbfc6.png)

Screenshot to illustrate the previously mentioned problem in AMOS, which might indicate why things are not translatable.

**Comment by koenr** [comment]
After some further investigation: 
- The language strings contain concatenation characters (see https://github.com/PlagScan/PlagScan_moodle/blob/master/lang/en/plagiarism_plagscan.php#L201-L207), which are not supported according to this documentation: https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings (bullet point 4 - please also consider bullet 2)

- You should get an error message for this at https://moodle.org/plugins/devzone.php?plugin=plagiarism_plagscan

Kind regards
Koen
