### ISSUE TITLE
Report level class set is always bad

### ISSUE THREAD

**Issue by adpe** [PlagScan/PlagScan_moodle#17]
It doesn't matter what the percent values are.

### Actual
![image](https://user-images.githubusercontent.com/9467708/70312940-e8100d00-1814-11ea-8bd4-ab5cd35f361a.png)
---
### Should
![image](https://user-images.githubusercontent.com/9467708/70312788-9a93a000-1814-11ea-8c8d-b019916f6ea6.png)
---
### Question
Does this classes will be set according the PlagScan settings

![image](https://user-images.githubusercontent.com/9467708/70313068-2f969900-1815-11ea-9e3a-de60829617b6.png)
---
Thanks for fixing that and helping out,
Adrian

**Comment by rolmedoh** [comment]
@adpe  Thanks for reporting it we need to replicate it on the dev system first.

**Comment by adpe** [comment]
Hello @rolmedoh 

Do you have some news about that? For me that's a crucial thing and should be resolved asap.

Greets,
Adrian

**Comment by adpe** [comment]
Hi @JesGor 

I'll point that and other misbehavior in the Moodle integration to your support team. Hope that this will be fixed soon...

Cheers,
Adrian

**Comment by JesGor** [comment]
Hi @adpe,

sorry for the late reply.

We have released a new version, we did some changes in the level classes to show the proper color/behaviour.

**Comment by adpe** [comment]
Hi @JesGor 

Yep just tried it twice and it works when I change the levels for the `admin` account in the PlagScan portal and refresh the view in Moodle. 

Thanks for fixing that, therefore marked as close.

Cheers,
Adrian
