### ISSUE TITLE
Several debugging notifications

### ISSUE THREAD

**Issue by adpe** [PlagScan/PlagScan_moodle#2]
Hello @rolmedoh @JesGor 

Can you please have a look at these debugging messages?
```
Coding problem: $PAGE->context was not set. You may have forgotten to call require_login() or $PAGE->set_context(). The page may not display correctly as a result
line 493 of /lib/pagelib.php: call to debugging()
line 1544 of /lib/pagelib.php: call to moodle_page->magic_get_context()
line 1880 of /lib/setuplib.php: call to moodle_page->initialise_theme_and_output()
line 1549 of /lib/formslib.php: call to bootstrap_renderer->__call()
line 199 of /lib/formslib.php: call to MoodleQuickForm->__construct()
line 44 of /plagiarism/plagscan/settings.php: call to moodleform->__construct()

Coding problem: $PAGE->context was not set. You may have forgotten to call require_login() or $PAGE->set_context(). The page may not display correctly as a result
line 493 of /lib/pagelib.php: call to debugging()
line 1544 of /lib/pagelib.php: call to moodle_page->magic_get_context()
line 1880 of /lib/setuplib.php: call to moodle_page->initialise_theme_and_output()
line 1549 of /lib/formslib.php: call to bootstrap_renderer->__call()
line 199 of /lib/formslib.php: call to MoodleQuickForm->__construct()
line 44 of /plagiarism/plagscan/settings.php: call to moodleform->__construct()

This page did not call $PAGE->set_url(...). Using https://<FQDN>/plagiarism/plagscan/settings.php
line 600 of /lib/pagelib.php: call to debugging()
line 820 of /lib/pagelib.php: call to moodle_page->magic_get_url()
line 4009 of /lib/navigationlib.php: call to moodle_page->__get()
line 759 of /lib/pagelib.php: call to settings_navigation->initialise()
line 820 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()
line 3390 of /lib/navigationlib.php: call to moodle_page->__get()
line 3434 of /lib/navigationlib.php: call to navbar->has_items()
line 626 of /theme/boost/classes/output/core_renderer.php: call to navbar->get_items()
line 42 of /theme/ffhsboost/layout/columns2.php: call to theme_boost\output\core_renderer->region_main_settings_menu()
line 1287 of /lib/outputrenderers.php: call to include()
line 1217 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 51 of /plagiarism/plagscan/settings.php: call to core_renderer->header()

Notice: Undefined property: stdClass::$plagscan_web in /<webpath>/moodle/plagiarism/plagscan/settings.php on line 107
Notice: Undefined property: stdClass::$plagscan_own_workspace in /<webpath>/moodle/plagiarism/plagscan/settings.php on line 107
Notice: Undefined property: stdClass::$plagscan_own_repository in /<webpath>/moodle/plagiarism/plagscan/settings.php on line 107
Notice: Undefined property: stdClass::$plagscan_orga_repository in /<webpath>/moodle/plagiarism/plagscan/settings.php on line 107
Notice: Undefined property: stdClass::$plagscan_plagiarism_prevention_pool in /<webpath>/moodle/plagiarism/plagscan/settings.php on line 107
Notice: Undefined property: stdClass::$plagscan_ssty in /<webpath>/moodle/plagiarism/plagscan/settings.php on line 107
Notice: Undefined property: stdClass::$plagscan_red in /<webpath>/moodle/plagiarism/plagscan/settings.php on line 107
Notice: Undefined property: stdClass::$plagscan_yellow in /<webpath>/moodle/plagiarism/plagscan/settings.php on line 107
```

**Comment by JesGor** [comment]
Thanks for the message.

We will take a look. Soon you will receive an answer.

**Comment by adpe** [comment]
There's much work todo, after updating a `Label` activitiy I get this error:
![image](https://user-images.githubusercontent.com/9467708/51102014-86e6e180-17dd-11e9-9fec-b3383d6d25c3.png)

Where can I find the old PlagScan version?

**Comment by JesGor** [comment]
Thanks for the message, we are working on Moodle trying to improve it and solve problems.

As I said this is a beta version. You can get the previous version which is stable in the Moodle Plugin directory: https://moodle.org/plugins/plagiarism_plagscan

**Comment by koenr** [comment]
I have the same problem as adpe after installing plagscan. I get the error message when updating quiz settings:

Fout in de programmeercode gevonden. Dit moet door een programmeur hersteld worden. moodle_database::update_record_raw() no fields found.

Meer informatie over deze fout

×Debug info: 
Error code: codingerror
×Stack trace:
line 1539 of /lib/dml/mysqli_native_moodle_database.php: coding_exception thrown
line 1589 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->update_record_raw()
line 768 of /plagiarism/plagscan/lib.php: call to mysqli_native_moodle_database->update_record()
line 253 of /plagiarism/plagscan/lib.php: call to plagscan_set_instance_config()
line 96 of /lib/plagiarismlib.php: call to plagiarism_plugin_plagscan->save_form_elements()
line 351 of /course/modlib.php: call to plagiarism_save_form_elements()
line 624 of /course/modlib.php: call to edit_module_post_actions()
line 152 of /course/modedit.php: call to update_moduleinfo()

The plagscan plugin I'm using is Scanplagiarism_plagscan | 3.0.02018121800 installed through the plugins database on Moodle.org. That is not a beta version I hope?

**Comment by JesGor** [comment]
This new commit fix the problems you mentioned:
- Few debugging messages
- Updating Label was throwing errors
- Updating Quiz was throwing errors

If you find any other thing please do not hesitate to open another issue.
Thanks.

**Comment by koenr** [comment]
Solved. Thanks!
