### ISSUE TITLE
Restore/duplication of assign activity broken when PlagScan installed

### ISSUE THREAD

**Issue by adpe** [PlagScan/PlagScan_moodle#20]
Dear @JesGor and @rolmedoh 

We've found a new bug, when doing a `backup + restore` of an `Assign` activity. The backup process finishes without problems, but when doign the restore it fails:

![image](https://user-images.githubusercontent.com/9467708/74849713-586cfb80-5339-11ea-8ede-96602522bd64.png)

Debugging message:
```php
[Wed Feb 19 16:56:39.667584 2020]
[php7:notice]
Default exception handler: error/setting_by_name_not_found Debug:
Error code: setting_by_name_not_found
$a contents: filename
line 124 of /backup/util/plan/base_plan.class.php: base_plan_exception thrown
* line 314 of /backup/util/helper/async_helper.class.php: call to base_plan->get_setting()
* line 606 of /backup/util/ui/renderer.php: call to async_helper::get_async_backups()
* line 462 of /lib/outputrenderers.php: call to core_backup_renderer->render_backup_files_viewer()
* line 541 of /backup/util/ui/renderer.php: call to plugin_renderer_base->render()
* line 166 of /backup/restorefile.php: call to core_backup_renderer->backup_files_viewer()
, referer: https://<FQDN>/course/view.php?id=<courseid>
```
**As I understand the PlagScan settings can not be set successful.**

Further I tried another way as we have a plugin installed in Moodle which duplicates courses. But unfortunately in the new course the predefined activity `with PlagScan enabled` will not be "imported/set" correct on the duplicated course activity.

**Please set this as a `high prio` as it breaks the whole restore process idea of Moodle for an activity!**

Greets,
Adrian

**Comment by JesGor** [comment]
Hello @adpe,

sorry again for the late reply on this.

With the latest version we tested to Backup as well as Restore, and all went trought without any errors. 

We tried to backup an assignment where PlagScan was enabled, and then restore it on the same course and in a different one, no problems on that. Also, we tried to backup and restore a entire course with assignments where PlagScan was enabled.

The only thing is, right now is not supported by our Moodle Plugin to backup/restore the assignments with the PlagScan settings being saved/imported correctly. So every time you restore an assignment where PlagScan was enabled, if you want to make it enable again it is necessary to set the options manually.

That said, we will take this into account and investigate this solution for future launches.

Thanks,
Jesús.

**Comment by adpe** [comment]
Hi @JesGor 

The problem still exists in our environment. As I see in the logs, I think you don't have the `async` backup functionality in Moodle enabled. Please do that and test again.

![image](https://user-images.githubusercontent.com/9467708/78769395-9d063200-798d-11ea-8b84-e31676884516.png)
```php
[Wed Apr 08 11:35:05.593972 2020]
[php7:notice]
Default exception handler: error/setting_by_name_not_found
Debug: 
Error code: setting_by_name_not_found
$a contents: filename
* line 124 of /backup/util/plan/base_plan.class.php: base_plan_exception thrown
* line 314 of /backup/util/helper/async_helper.class.php: call to base_plan->get_setting()
* line 606 of /backup/util/ui/renderer.php: call to async_helper::get_async_backups()
* line 462 of /lib/outputrenderers.php: call to core_backup_renderer->render_backup_files_viewer()
* line 541 of /backup/util/ui/renderer.php: call to plugin_renderer_base->render()
* line 166 of /backup/restorefile.php: call to core_backup_renderer->backup_files_viewer()
, referer: https://FQDN/backup/restore.php
```

HTH,
Adrian

**Comment by JesGor** [comment]
Hi @adpe,

thanks for the input. We will try following the instruction you said.

Could you tell me which version of Moodle are you using?

Thanks,
Jesús.

**Comment by adpe** [comment]
Hi @JesGor 

We're using 3.7.5 and the `async` functionality was introdocuted in 3.7, see https://docs.moodle.org/38/en/Course_backup#Asynchronous_course_backups + https://tracker.moodle.org/browse/MDL-28505.

HTH,
Adrian

**Comment by JesGor** [comment]
Hi @adpe 

We were trying to replicate the problem, but we couldn not see the same error, we actually could backup and restore an Assignment activity successfully.

We have installed a Moodle instance with the same version you mentioned (3.7.5).

![image](https://user-images.githubusercontent.com/11158886/80224943-b4f6da80-864a-11ea-87bd-d8d6c1823194.png)

We enabled the Asynchronous backups as well.

![image](https://user-images.githubusercontent.com/11158886/80225076-e1aaf200-864a-11ea-9b24-4fa83746119d.png)

Taking an assignment where PlagScan Plugin was enabled, and also containing files on it (checked by PlagScan too). We run a backup of the assignment succesfully:

![image](https://user-images.githubusercontent.com/11158886/80225444-5e3dd080-864b-11ea-8884-5db9ade6a6c0.png)


![image](https://user-images.githubusercontent.com/11158886/80225356-40706b80-864b-11ea-9bf8-67d56312a8c8.png)

Once we got the backup file, we tried to run a few restore attempts, and those were successfully too.

![image](https://user-images.githubusercontent.com/11158886/80225500-744b9100-864b-11ea-9b97-e0f8f34c8fbf.png)

![image](https://user-images.githubusercontent.com/11158886/80225723-b83e9600-864b-11ea-9eaa-0252a2ab6e82.png)

As long as we can not see anything related to plagscan plugin or plagiarism plugin on the logs you sent, it is difficult for us to find a solution to this.

Maybe contacting with Moodle support could be helpful on this case.

Sorry for the inconvinience.

Regards,
Jesús.

**Comment by adpe** [comment]
Hello @JesGor 

I can't reproduce the error at the moment, but the only changes was plugin bump (plagscan) and we updated Moodle, from 3.7.4 to 3.7.5, on 1. April 2020. But the error existed before, so I think it must be related something to your plugin.

But anyway as this error is not occuring anymore, we can half-close this issue.

<hr>

The other point I mentioned in https://github.com/PlagScan/PlagScan_moodle/issues/20#issue-567662317 is still open/broken: 
> Further I tried another way as we have a plugin installed in Moodle which duplicates courses. But unfortunately in the new course the predefined activity with PlagScan enabled will not be "imported/set" correct on the duplicated course activity.

This also happens when you just try to duplicate an activity, it will be copied but the plagscan configuration will not be inherited/copied to the new one:
![image](https://user-images.githubusercontent.com/9467708/80362015-31bfc980-8882-11ea-8a92-6628a91bba3d.png)

Imagine, you have a template course and you have there defined the plagscan configuration in activities and you will copy this course in to 20 new ones. So must you set this configuration manually in all the new courses, that's not like it should behave.

Greets,
Adrian

**Comment by adpe** [comment]
Hi @JesGor 

I've working code to fix the `backup&restore` and `duplicate` functionality. I'll make a PR soon and fork this repo.

What I'm not sure about is the submissionid field. It is only set when `multipleaccounts` is configured, why not when working with only one `main account`?

Cheers,
Adrian

**Comment by adpe** [comment]
Here we go https://github.com/PlagScan/PlagScan_moodle/pull/21

**Comment by JesGor** [comment]
This was made for compatibility with assignments created with old version of the plugin.
