### ISSUE TITLE
Make plugin Moodle >= 3.11 compatible

### ISSUE THREAD

**Issue by adpe** [PlagScan/PlagScan_moodle#26]
Hello @JesGor 

I've created this issue, so that it doesn't get lost. The change in core I mentioned here https://github.com/PlagScan/PlagScan_moodle/pull/21#issuecomment-653743077 in the "update" section is finally integrated into master and 3.11 (https://tracker.moodle.org/browse/MDL-69202). As mentioned in the MoodleDocs https://docs.moodle.org/dev/Integration_Review#backporting, this will not be a candidate for back porting.

Can you please add this issue on your "plan", when releasing the plugin to be compatible with Moodle 3.11? The best would be, if you create separate branches for Moodle stable versions. Useful information can be found here https://docs.moodle.org/dev/version.php#Plugin_version_properties.

We'll update our Moodle environment in Mid of July 2021 to Moodle 3.11. So it would be good, if you will take care of this issue around May/June 2021, when Moodle will release version 3.11

Thank you very much,
Adrian

**Comment by mifantrax** [comment]
Subscribing to the same, we are looking at upgrading in June please ensure compatibility.

**Comment by adpe** [comment]
The relevant tracker stuff I mentioned here should be refactored in a new issue. As this change will only affect the Moodle 3.11 version. But as PlagScan doesn't support multiple stable branches, it will probably not be done yet.

I can confirm that with Moodle 3.11+ (Build: 20210527), PHP 7.4.20 and the plagscan plugin version 3.2.1 (2021060900) the debugging messages from #22 are resolved and the new version was released.

Therefore, I'll close this issue. Finally, done and thanks!

Greets
Adrian
