### ISSUE TITLE
Move language strings out of code

### ISSUE THREAD

**Issue by koenr** [PlagScan/PlagScan_moodle#3]
Low priority
Apart from en, there should be no language strings shipped with the code of the module as per https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

You can send the strings to the language pack maintainer of es and de or I can move the existing es and de strings to the language portal if you like. They are not there at the moment.

**Comment by adpe** [comment]
Hi @koenr 

It would be great, if you can translate this plugin over AMOS. With the new overview in the plugins repo (https://moodle.org/plugins/translations.php?plugin=plagiarism_plagscan) the language stats are visible. 

Please don't copy & paste all translations. As I see this one https://github.com/PlagScan/PlagScan_moodle/blob/master/lang/de/plagiarism_plagscan.php#L29 is wrong.

**Comment by koenr** [comment]
Yes, that is why the best place for the translation is in
https://lang.moodle.org. Anyone can improve the strings in that case. I
noticed some English in the Spanish version.
I was thinking of uploading the strings as they are to the language portal
and commit them, but it is may be better to the language pack maintainer
for a review. Is that ok for you? If you send the strings yourself, your
name will be under it, otherwise mine and I didn't do the work. Please let
me know how to proceed

I noticed that in version 3.0.2 the string useplagscan_help |
plagiarism_plagscan is still missing.
I suggested to Davide to add

Start manually: you will have to check each document manually.
* Start immediately: the PlagScan plugin will start analyzing documents
automatically and immediately after uploading.
* Start immediately after the first due date: the PlagScan plugin only
starts when the first due date has passed. Otherwise, you can use the
plugin manually or deactivate it completely.
* Start immediately after all due dates: the plugin will begin analyzing
the documents right after every deadline.

From
https://api.plagscan.com/v3/PlagScan_Moodle_Manual-Teachers-Instructors_EN.pdf

It's quite essential help to get what the settings mean.

Kind regards

Koen

Op ma 11 feb. 2019 om 10:41 schreef Adrian Perez <notifications@github.com>:
